language: node_js
node_js:
  - 8
cache:
  - node_modules
script:
  - npm run build
  - npm run test:coverage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master